description: >
  Install skaffold for your job.
# What will this command do?
# Descriptions should be short, simple, and clear.
steps:
  - run:
      name: install skaffold
      command: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install skaffold /bin/
  - run:
      name: confirm
      command: skaffold version
