name: update all package

on:
  repository_dispatch:
    types: [ orbs-* ]

jobs:
  update:
    runs-on: ubuntu-latest
    name: update
    steps:
    - name: Generate Access Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_FORGITHUBACTIONS_ID }}
        private_key: ${{ secrets.APP_FORGITHUBACTIONS_KEY }}

    - name: set env
      run: |
        echo "REPO_NAME=`echo ${{ github.event.action }}`" >> $GITHUB_ENV
        echo "ACCESS_TOKEN=`echo ${{ steps.generate_token.outputs.token }}`" >> $GITHUB_ENV

    # alpha
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        ref: refs/heads/alpha
        fetch-depth: 0
        token: ${{ env.ACCESS_TOKEN }}

    - name: Update subpackage
      run: |
        (
          cd ..
          git clone https://github.com/RHEMS-Japan/${{ env.REPO_NAME }}.git
        )
        cp ../${{ env.REPO_NAME }}/src/commands/*.yml  src/commands  || true
        cp ../${{ env.REPO_NAME }}/src/jobs/*.yml      src/jobs      || true
        cp ../${{ env.REPO_NAME }}/src/scripts/*.sh    src/scripts   || true
        cp ../${{ env.REPO_NAME }}/src/executors/*.yml src/executors || true
        cp ../${{ env.REPO_NAME }}/src/tests/*.bats    src/tests     || true

    - name: Git commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci]"
        branch: refs/heads/alpha

    - name: Git push
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: refs/heads/alpha
        github_token: ${{ secrets.GITHUB_TOKEN }}


    # master
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        fetch-depth: 0
        token: ${{ env.ACCESS_TOKEN }}

    - name: Update subpackage
      run: |
        (
          cd ..
          git clone https://github.com/RHEMS-Japan/${{ env.REPO_NAME }}.git
        )
        cp ../${{ env.REPO_NAME }}/src/commands/*.yml  src/commands  || true
        cp ../${{ env.REPO_NAME }}/src/jobs/*.yml      src/jobs      || true
        cp ../${{ env.REPO_NAME }}/src/scripts/*.sh    src/scripts   || true
        cp ../${{ env.REPO_NAME }}/src/executors/*.yml src/executors || true
        cp ../${{ env.REPO_NAME }}/src/tests/*.bats    src/tests     || true

    - name: Git commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[semver:patch]"
        branch: refs/heads/master

    - name: Git push
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: refs/heads/master
        github_token: ${{ secrets.GITHUB_TOKEN }}