name: update all package

on:
  repository_dispatch:
    types: [ orbs-* ]

jobs:
  update:
    runs-on: ubuntu-latest
    name: update
    steps:
    - name: Generate Access Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_FORGITHUBACTIONS_ID }}
        private_key: ${{ secrets.APP_FORGITHUBACTIONS_KEY }}

    - name : set env
      run: echo "ACCESS_TOKEN=`echo ${{ steps.generate_token.outputs.token }}`" >> $GITHUB_ENV

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        ref: refs/heads/alpha
        fetch-depth: 0
        token: ${{ env.ACCESS_TOKEN }}

    - name: Update subpackage
      run: |
        (
          mkdir ../orbs && cd $_
          git clone https://github.com/RHEMS-Japan/orbs-k8s-tools.git
          git clone https://github.com/RHEMS-Japan/orbs-blue-deploy.git
          git clone https://github.com/RHEMS-Japan/orbs-cisync.git
        )
        for dir in $(find ../orbs -maxdepth 1 -type d); do
          cp ${dir}/src/commands/*.yml src/commands
          cp ${dir}/src/jobs/*.yml     src/commands
          cp ${dir}/src/scripts/*.sh   src/commands
          cp ${dir}/src/tests/*.bats   src/commands
        done

    # Commit
    - name: Git commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci]"
        branch: refs/heads/alpha

    # Push
    - name: Git push
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: refs/heads/alpha
        github_token: ${{ secrets.GITHUB_TOKEN }}